feat: ✨ add pre commit hook using husky and lint-staged

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,9 @@
 #!/usr/bin/env bash
-pnpm lint-staged
+echo 'Running pre commit checks...'
+
+pnpm run commit:pre || (
+	echo '❌ There was a problem with your code. Run `pnpm lint-staged` to see the errors.'
+	false;
+)
+
+echo '✨🚀🏄‍♂️🍻 No error found. Running commitizen now...'
